### PR TITLE
Allows requests for custom crops on the fly and not just predefined crops

### PR DESCRIPTION
**Pull request by ProNotion**
I needed to create a custom build in order to replace existing unnamed crops and also pass a crop mode. This change satisfies that requirement and I am sure will be useful to others as makes the library generally more flexible.

### CODE REVIEW

**Comment by Jeavon** [comment]
Sorry I missed this for sooo long! 

I'm not sure how these methods differ from the GetResponsiveImageUrl methods apart from you are allowing ImageCropMode to be specified?

**Comment by ProNotion** [comment]
`GetResponsiveImageUrl` only returns the image path as far as I know, at the moment if you want a cropped image you only have the option to use a named crop. This PR opens up the ability to have some control over crops without having to configure them first.

**Comment by Jeavon** [comment]
GetResponsiveImageUrl does crop without having a predefined crop according to the width and height parameters passed in. The reason there are two methods instead of one is for the dynamics extension method support where parameter type is not considered. However there isn't a option to currently specify a ImageCropMode, it's always crop

**Comment by ProNotion** [comment]
I've come up against this on another project and for some reason I only see the following overloads with Intellisense:

    public static string GetResponsiveCropUrl(this IPublishedContent publishedContent, string cropAlias);
    public static string GetResponsiveCropUrl(this IPublishedContent publishedContent, string cropAlias, string propertyAlias);
    public static string GetResponsiveCropUrl(this IPublishedContent publishedContent, string cropAlias, string propertyAlias, string outputFormat);

If I decompile it via Resharper I see the following in addition to the above:

    public static string GetResponsiveImageUrl(this IPublishedContent publishedContent, int width, int height);
    public static string GetResponsiveImageUrl(this IPublishedContent publishedContent, int width, int height, string propertyAlias);
    public static string GetResponsiveImageUrl(this IPublishedContent publishedContent, int width, int height, string propertyAlias, string outputFormat);

But the ones with explicit width/height parameters are unavailable to me? If I attempt to use them I get an exception:

    CS1928: 'Umbraco.Core.Models.IPublishedContent' does not contain a definition for 'GetResponsiveCropUrl' and the best extension method overload 'Slimsy.Slimsy.GetResponsiveCropUrl(Umbraco.Core.Models.IPublishedContent, string, string)' has some invalid arguments

Any ideas why that might be? Seems a bit strange!

**Comment by ProNotion** [comment]
Ignore me! I just realised that the name of the methods are different `GetResponsiveImageUrl` rather than `GetResponsiveCropUrl`, I really should learn by now to look at the obvious!

**Pull request closed without merging**
