### PR TITLE
Add app settings for hard coded variables

### PR DESCRIPTION
**Pull request by tcmorris**
Hey,

I noticed a couple of comments in the code about making these variables configurable, so I've added the app settings for width step and max width.

I've also introduced an app setting for default quality, so that can also be changed if you want.

### CODE REVIEW

**Comment by tcmorris** [comment]
Just noticed that it looks like `develop` is the chosen branch for adding new code rather than `feature` > `master` (i.e. GitHub Flow). Let me know if this isn't using correct procedure and I'll update.

**Comment by Jeavon** [comment]
Looks awesome! Thanks!

If you could target the PR to the develop branch that would be great, thanks again!

**Comment by tcmorris** [comment]
No worries, that's updated :) 
(excuse the duplicate merge, github seemed to think I hadn't resolved the conflict)

**Comment by Jeavon** [comment]
Awesome, many thanks!

**Pull request merged**
